app = 'tlgm-vehiculos'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']
  idle_timeout = '300s'

  # CONFIGURACIÓN DE DESPERTADO AGRESIVA
  [[http_service.checks]]
    grace_period = "35s"  # Aumentado a 35s: da tiempo real a Telethon para conectar
    interval = "20s"      # Revisa más seguido una vez que arranca
    method = "GET"
    timeout = "5s"        # Espera hasta 5s por la respuesta de Flask
    path = "/health"

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
